apiVersion: v2
name: sealed-secrets
description: A Helm chart to deploy sealed secrets into an openshift cluster
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: sealed-secrets
    version: 2.1.8
    repository: https://bitnami-labs.github.io/sealed-secrets
  - name: service-account
    version: 0.6.0
    repository: https://charts.cloudnativetoolkit.dev/
