service-account:
  name: sealed-secrets
  create: false
  sccs:
    - anyuid
sealed-secrets:
  networkPolicy:
    enabled: false
  nodeSelector: {}
  podLabels: {}
  resources: {}
  affinity: {}
  securityContext:
    fsGroup: ''
    runAsUser: ''
  rbac:
    create: true
    pspEnabled: false
  crd:
    create: true
    keep: true
  ingress:
    annotations: {}
    enabled: false
    hosts:
      - chart-example.local
    path: /v1/cert.pem
    tls: []
  serviceAccount:
    create: true
    name: sealed-secrets
  image:
    pullPolicy: IfNotPresent
  #  repository: >-
  #    quay.io/bitnami/sealed-secrets-controller@sha256:8e9a37bb2e1a6f3a8bee949e3af0e9dab0d7dca618f1a63048dc541b5d554985
  secretName: sealed-secret-key
  tolerations: []
  controller:
    create: true
  priorityClassName: ''
  podAnnotations: {}
