service-account:
  name: sealed-secrets
  create: false
  sccs:
    - anyuid
sealed-secrets:
  networkPolicy:
    enabled: false
  nodeSelector: {}
  podLabels: {}
  resources: {}
  affinity: {}
  securityContext:
    fsGroup: ''
    runAsUser: ''
  rbac:
    create: true
    pspEnabled: false
  crd:
    create: true
    keep: true
  ingress:
    annotations: {}
    enabled: false
    hosts:
      - chart-example.local
    path: /v1/cert.pem
    tls: []
  serviceAccount:
    create: true
    name: sealed-secrets
  image:
    pullPolicy: IfNotPresent
    #repository: >-
      #registry.hub.docker.com/bitnami/sealed-secrets-controller@sha256:ba6e4a30893cafd8a8e909049f7d2b92e2267ffe48b880232bd9020adf448e48
  secretName: sealed-secret-key
  tolerations: []
  controller:
    create: true
  priorityClassName: ''
  podAnnotations: {}
sealed-secrets:

